# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ead96fb007c9fbfd17451ee7405c9c0c2b7c75394f542e338c1fd961af4357f62ed46772d3574f7b3849429fa2649d065878dfc38e42806c8e18a8ca7476247e

test:
  secret_key_base: b574dd3c391466cb866ab0acb24b6d653fbf924cf340c438092cbd507755500c8d064799070bedbdb138d843ed0f6119a10a1d6f13f2869aa215837bf2635fb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
